# Generated by Django 5.1.2 on 2024-10-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='history',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
